# Site Settings
url:                https://skz.dev
title:              Sasha Kuznetsov
description:        "Software engineer, physicist, and hacker."
author:
  name:             Sasha Kuznetsov
  twitter:          _skzv
twitter:
  username:         _skzv
  card:             summary_large_image

# Other Settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - sasha-kuznetsov-design-system

defaults:
  -
    values:
      layout:       "compress"
      image:        https://skz.dev/assets/img/preview-banner.png